[build]
builder = "NIXPACKS"
buildCommand = "npm install --build-from-source && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[deploy]
startCommand = "node server/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
